version: '2'
services:
  runner:
    image: 'gitlab/gitlab-runner:v12.8.0'
    container_name: runner
    volumes:
      - 'moodle_data:/bitnami'
    restart: always
  moodle:
    image: 'bitnami/moodle:3'
    container_name: moodle
    environment:
      - MARIADB_HOST=$MARIADB_HOST
      - MARIADB_PORT_NUMBER=$MARIADB_PORT_NUMBER
      - MOODLE_DATABASE_USER=$MOODLE_DATABASE_USER
      - MOODLE_DATABASE_NAME=$MOODLE_DATABASE_NAME
      - MOODLE_DATABASE_PASSWORD=$MOODLE_DATABASE_PASSWORD
      - MOODLE_SKIP_INSTALL=$MOODLE_SKIP_INSTALL
    volumes:
      - 'moodle_data:/bitnami'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - runner
    restart: always
volumes:
  moodle_data:
    driver: local
