version: '2'
services:
  runner:
    image: 'gitlab/gitlab-runner:v12.8.0'
    volumes:
      - './runner-config.toml:/etc/gitlab-runner/config.toml'
      - 'moodle_data:/bitnami'
    restart: always
  moodle:
    image: 'bitnami/moodle:3'
    env_file: moodle.env
    volumes:
      - 'moodle_data:/bitnami'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - runner
    restart: always
volumes:
  moodle_data:
    driver: local
